### DEMO 2: GENERADORES

#### FUNCIONES

In [ ]:
# función normal
def suma(a, b):
    c = a + b
    return c


In [7]:
# prueba función

c = suma(2,3)

print(c)

5


#### GENERADORES

In [8]:
# generador
def suma2(a, b):
    c = a + b
    yield c
    d = c*2
    yield d
    d = 100
    yield d

In [14]:
# prueba generador
c = suma2(2,3)

print(c)

<generator object suma2 at 0x7ff450728ac0>


In [15]:
# prueba generador
z = next(c)
print(z)


5


In [16]:
# prueba generador
print(next(c))

10


In [19]:
# prueba de multiples generadores

c1 = suma2(2, 3)
c2 = suma2(10, 1)

print(next(c1))
print(next(c1))
print(next(c2))
print(next(c1))
print(next(c2))
print(next(c2))

5
10
11
100
22
100


#### NÚMEROS ALEATORIOS

In [20]:
import numpy as np

In [21]:
np.random.choice([1,2,3,4,5,6], size=5)

array([2, 5, 4, 4, 5])

In [22]:
np.random.choice([1,2], size=5, p=[0.5,0.5])

array([2, 1, 1, 2, 1])

In [23]:
np.random.exponential(scale=1.7, size=4)

array([0.13616189, 5.07508505, 1.09922111, 4.29565707])

In [24]:
np.random.normal(loc=10,scale=2, size=4)

array([ 9.10855961, 12.19971174,  5.99885314,  6.58864529])

In [25]:
np.random.binomial(n=10, p=.2, size=10)

array([3, 5, 2, 2, 4, 1, 3, 1, 1, 3])